// Falk AdSolution - Copyright (c) 2003 by Falk eSolutions AG - All rights reserved
function nB(Na)
{document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+Na+'"></scr'+'ipt>');}function oB(Oa)
{if(Oa==-1)
return ';path=/';var Pa=new Date();Pa.setTime(parseInt(Pa.getTime(),10)+1000*60*parseInt(Oa,10));return ';path=/;expires='+Pa.toGMTString();}function pB(j,k,A)
{var i='&dlv='+Ads_nid+','+Ads_wid+','+Ads_iid+','+j+','+k+'&kid='+j+'&chw='+bA+'&tcs='+cA+A+vA+gA;i+='&dmn='+Ads_T[5];if(navigator.appVersion.substring(0,1)>'3')
{i+='&scx='+screen.width+'&scy='+screen.height+'&scc='+screen.colorDepth;if(navigator.javaEnabled())
i+='&jav=1';}if((Ads_wrd!='')&&(Ads_wrd.toLowerCase()!='[keyword]'))
{i+='&wrd='+escape(Ads_wrd);}var Qa='&sta=,,,,'+aC()+',,,,'+escape(Ads_T[7])+',';xB(1,'STA-Uri-Parameter',Qa);i+=Qa;return (Ads_Timestamp+i);}function qB(j,k,A)
{return '&rdm='+pB(j,k,A)+'&iid='+Ads_iid+'&bid='+k;}function rB()
{if(hA)
return kA[Ads_sec]+'/dat/dlv/aslcount-small.html;cmd=red&';else
return kA[Ads_sec]+'/dat/bgf/trpix.gif?';}function sB(i)
{xB(1,'',rB()+i);var Ra='<img src="'+rB()+i+'" width="1" height="1">';if(hA)
Ra='<iframe src="'+rB()+i+'" width="1" height="1" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0">'+Ra+'</iframe>';Ra=bC('Ads_Count'+Ads_iid)+Ra+cC();return ((Ads_opt&512)==0)?Ra:'';}function tB(v,i)
{v.document.write(sB(i));}function uB()
{return vB(Math.random()*100000000,8);}function vB(Sa,Ta)
{var Ua='#'+(Sa+100000000);return Ua.substr(10-Ta,Ta);}function wB(Va,Wa,Xa)
{var s;while((s=Va.indexOf(Wa))!=-1)
Va=Va.substr(0,s)+Xa+Va.substring(s+Wa.length,Va.length);return Va;}function xB(E,Va,Ya)
{var Za=new Date();if(Ads_debug==1)
{document.write(((E!=3)?'':'<br>')+'<font color=#0000ff>[DEBUG'+((Za-iA)/1000)+']</font> ');if((E==0)||(E==3))
document.write('<b><big>'+Va+'</big></b><br>');else if(E==1)
document.write(''+Va+': &nbsp;<font color=#000080>'+Ya+'</font><br>');else
document.write('<b>'+Va+'</b><br>');}else if((Ads_debug==2)&&(E==3))
document.write('<font color=#0000ff>[DEBUG'+((Za-iA)/1000)+']</font> <b><big>'+Va+'</big></b><br>');}function yB(Ab)
{var D='#'+(parseInt(Ab,10)+100000000);return D.substr(2,2)+'/'+D.substr(4,2)+'/'+D.substr(6,2)+'/'+D.substr(8,2);}function zB(Sa)
{var Bb='0123456789ABCDEF';var Cb='';while(Sa>0)
{Cb=Bb.substr(Sa%16,1)+Cb;Sa=parseInt(Sa/16,10);}return (Cb=='')?'0':Cb;}function aC()
{if(typeof(gintFlash)!='undefined')
return gintFlash;var Db;gintFlash=0;if(((navigator.appName=="Netscape")&&(navigator.userAgent.indexOf("Mozilla")!=-1)&&(parseFloat(navigator.appVersion)>=4)&&(navigator.javaEnabled())&&navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin))
{Db=navigator.plugins['Shockwave Flash'].description;Db=Db.substring(Db.indexOf("."),-1);gintFlash=Db.substr(-1);}else if(navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Windows")!=-1&&navigator.userAgent.indexOf("Windows 3")==-1&&document.all)
{document.write('<scr'+'ipt language=VBScript>\n cB=10\nintMinVersion=1\nDo\nOn Error Resume Next\n');document.write('bolFlash=(IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash."&cB)))\n');document.write('If bolFlash=true Then Exit Do\ncB=cB-1\nLoop While cB>=intMinVersion\n </scr'+'ipt>');gintFlash=cB;}return gintFlash;}function bC(Eb)
{if(typeof(document.getElementsByTagName)!='undefined'&&typeof(document.createElement)!='undefined')
return '<div id='+Eb+' style="position:absolute;left:0;top:0;display:none;">';else if(document.layers)
return '<layer id=Ads_Banner'+Ads_iid+' left="0" top="0" visibility="hide">';else
return '<div id=Ads_Banner'+Ads_iid+' style="position:absolute;left:0;top:0;visibility:hidden;">';}function cC()
{return (document.layers?'</layer>':'</div>');}function dC(Fb)
{var Gb,Hb;if(window.innerHeight)
{Gb=Fb.x;Hb=Fb.y;}else
{if(Fb.offsetLeft)
{Fb=Fb;Gb=Fb.offsetLeft;Yg=Fb.offsetParent;while(Yg!=null)
{Gb+=Yg.offsetLeft;Yg=Yg.offsetParent;}Hb=Fb.offsetTop;Yg=Fb.offsetParent;while(Yg!=null)
{Hb+=Yg.offsetTop;Yg=Yg.offsetParent;}}else
return [-1000,-1000];}return [Gb,Hb];}function eC(Ib,B,m,n)
{var Jb;var Fb=document.images[B];var Kb=dC(Fb);Fb.width=m;Fb.height=n;if(uA)
Jb=document.getElementById(Ib).style;else if(document.layers)
Jb=document.layers[Ib];else
Jb=document.all[Ib].style;Jb.left=Kb[0];Jb.top=Kb[1];if (uA) Jb.display='block';else if(document.layers) Jb.visibility='show';else Jb.visibility='visible';}// Falk AdSolution - Copyright (c) 2003 by Falk eSolutions AG - All rights reserved
var Ads_ModulMain=true;if(typeof(Ads_ModulEffects)=='undefined')
Ads_ModulEffects=false;var bA,cA,dA,eA,fA,gA,hA,iA;var jA=['http://a.as-us.falkag.net','https://s.as-us.falkag.net'];var kA=['http://red01.as-us.falkag.net','https://red01.as-us.falkag.net'];var lA=['http://red01.as-us.falkag.net/server/asldata.js','https://red01.as-us.falkag.net/server/asldata.js'];var mA=['http://b.as-us.falkag.net','https://s.as-us.falkag.net'];var nA=['http://b.as-us.falkag.net/','https://s.as-us.falkag.net/'];var oA=[];var pA=navigator.userAgent.toLowerCase();var qA=(pA.indexOf("msie")!=-1);var rA=((pA.indexOf("win")!=-1)||(pA.indexOf("16bit")!=-1));var sA=(pA.indexOf("mac")!=-1);var tA=(navigator.appName.indexOf('icrosoft')!=-1);var uA=(typeof(document.getElementsByTagName)!='undefined'&&typeof(document.createElement)!='undefined')?1:0;var vA='';var wA=0;var xA=[];var yA=[];var zA;var a=[];var b=[];var c=[];var d=[];var e=[];var f=[];var g=[];var Ads_LinkUrl,Ads_CountUrl,Ads_ClickUrl,Ads_T,iid,bid,rdm;var aB,bB,cB;var dB='toolbar=yes,directories=yes,status=yes,scrollbars=yes,resizable=yes,menubar=yes,location=yes';function gotoSite(){window.open(aB,'flashwin',dB);}function emosite(){window.open(aB,'flashwin',dB);}function FlashClick(){window.open(aB,'flashwin',dB);}function link1(){window.open(aB,'flashwin',dB);}function gotoURL(h){window.open(bB+escape(h),'flashwin',dB);}function eB()
{Ads_kid=0;Ads_bid=0;Ads_cmd='';}function fB(h)
{xB(1,'adsclickurl',Ads_ClickUrl);h=wB(h,'[par]',escape(Ads_par));h=wB(h,'[keyword]',escape(Ads_wrd));h=wB(h,'[timestamp]',Ads_Timestamp);h=wB(h,'[clickurl]',escape(Ads_CountUrl));h=wB(h,'[clickurl_plain]',Ads_CountUrl);h=wB(h,'[web_id]',Ads_wid);h=wB(h,'[web_external_id]',escape(Ads_xwid));h=wB(h,'[con_id]',Ads_iid);h=wB(h,'[con_external_id]',escape(Ads_xiid));return h;}function gB()
{return kA[Ads_sec]+'/dat/dlv/aslcount.html?cmd=url&';}function hB(h,i)
{return gB()+i+'&dat='+escape(h);}function iB(j,k,l,m,n)
{var o;if(wA<2)
{wA++;o=wA+1;vA+='&kid'+o+'='+j;vA+='&bid'+o+'='+k;vA+='&iid'+o+'='+Ads_iid;vA+='&dlv'+o+'='+Ads_nid+','+Ads_wid+','+Ads_iid+','+j+','+k;if(fA!=0)
vA+='&sid'+o+'='+fA;arrIntern=l.split('-');Ads_iid=arrIntern[1];Ads_kid=arrIntern[2];Ads_bid=(arrIntern.length<4)?0:arrIntern[3];Ads_par=(arrIntern.length<5)?Ads_par:unescape(arrIntern[4]);Ads_xl=m;Ads_yl=n;nB(jA[Ads_sec]+'/dat/cjf/'+yB(Ads_iid)+'.js');}else
{vA='';wA=0;eB();}}function jB(p)
{var q=[];var r=p.length;var s;for(s=0;s<r;s+=2)
q[s/2+1]=Ads_CountUrl+escape(p[s+1])+'&bidx='+p[s];return q;}function SAS()
{var t='undefined';if(typeof(Ads_cmd)==t) Ads_cmd='';if(typeof(Ads_kid)==t) Ads_kid=0;if(typeof(Ads_bid)==t) Ads_bid=0;if(typeof(Ads_xl)==t) Ads_xl=0;if(typeof(Ads_yl)==t) Ads_yl=0;if(typeof(Ads_xp)==t) Ads_xp='';if(typeof(Ads_yp)==t) Ads_yp='';if(typeof(Ads_opt)==t) Ads_opt=0;if(typeof(Ads_wrd)==t) Ads_wrd='';if(typeof(Ads_prf)==t) Ads_prf='';if(typeof(Ads_par)==t) Ads_par='';if(typeof(Ads_cnturl)==t) Ads_cnturl='';if(typeof(Ads_ref)==t) Ads_ref=0;if(typeof(Ads_anc)==t) Ads_anc='';if(typeof(Ads_cmb)==t) Ads_cmb=[];Ads_cmd=Ads_cmd.toLowerCase();if(Ads_ref==0)
Ads_ref=IAS[12];if(Ads_ref>0)
{document.write('<iframe src="'+jA[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid+'&kid='+Ads_kid+'&bid='+Ads_bid+'&xl='+Ads_xl+'&yl='+Ads_yl+'&xp='+Ads_xp+'&yp='+Ads_yp+'&opt='+Ads_opt+'&wrd='+escape(Ads_wrd)+'&prf='+escape(Ads_prf)+'&par='+escape(Ads_par)+'&cnturl='+Ads_cnturl+'&sec='+Ads_sec+'&ref='+Ads_ref+'" width="'+Ads_xl+'" height="'+Ads_yl+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');Ads_ref=0;return;}xB(3,'Start for Adspot '+Ads_iid);gD();bA='';cA='';eA=0;fA=0;gA='';dA=-1;if((typeof(Ads_T)=='undefined')||(typeof(Ads_T[5])=='undefined'))
Ads_T=[0,0,'',0,0,'','','','',0,0,0];if(Ads_nid==7)
KAS[KAS.length]=[-1,100,-1,100,[],0,0,0,0,100];xB(3,'Select campaigns');if((Ads_kid==0)||(Ads_kid==''))
dA=iC();else
{xB(1,'Preselected campaign',Ads_kid);r=KAS.length;dA=0;while((dA<r)&&(KAS[dA][0]!=Ads_kid))
dA++;if(dA==r)
dA=-1;}if((Ads_opt&256)!=0)
{if(dA!=-1)
Ads_skid=KAS[dA][0];else
Ads_skid=0;xB(1,'Skipping delivery,selected campaign:',Ads_skid);}else
{if(dA!=-1)
{eA=KAS[dA][0];fA=KAS[dA][6];if(fA!=0)
gA='&sid='+fA;xB(1,'Selected campaign',eA+'('+fA+')');if(eA>0)
{xB(1,'BJF-load start','');nB(jA[Ads_sec]+'/dat/bjf/'+yB(eA)+'.js');xB(1,'BJF-load ende','');}else
DAS();}else
{xB(1,'no campaign selected!');DAS();}}}function DAS()
{xB(3,'Select banner for campaign '+eA);var u,r,i,v,w,x,y,z;var A='';var B='';var C=['_blank','_self','_parent','_top'];var k=0;var D,m,n;if(IAS[9]==1)
{D='adsolut.gif';m=234;n=60;}else
{D='trpix.gif';m=1;n=1;}var E=1;var h='http://www.falkag.de';// Ziel-Url
var F='Falk AdSolution';var G=0;var H='';var I='';var J='';var K='';var L='';var M=0;var N=0;var O=1;var P=2;var l='';var Q='';var p=[];var R=0;var S='';var T,U,V,W,X,Y,Z,Aa,Ba,Ca;if(eA!=0)
{if((Ads_bid==0)||(Ads_bid==''))
u=jC(dA,eA);else
{r=BAS.length;u=0;while((BAS[u][0]!=Ads_bid)&&(u<r))
u++;if(u==r)
u=-1;}if(u!=-1)
k=BAS[u][0];}if(k>0)
{E=BAS[u][3];D=BAS[u][4];h=BAS[u][5];F=BAS[u][6];G=BAS[u][12];H=BAS[u][7];I=BAS[u][8];J=BAS[u][9];K=BAS[u][10];L=BAS[u][11];m=BAS[u][13];n=BAS[u][14];M=BAS[u][15];N=BAS[u][16];O=BAS[u][17];P=BAS[u][18];l=BAS[u][19];Q=BAS[u][20];p=BAS[u][22];R=BAS[u][23];S=BAS[u][24];A=iD(eA,dA,k,u,((G&4096)>0));Ads_klist+=eA+'#';x=KAS[dA][4][25];if(x>0)
{if(typeof(Ads_fcount[x])=='undefined')
Ads_fcount[x]=1;else
Ads_fcount[x] ++;}}if(eA==-1)
{eA=99999999;k=99999999;}Ads_skid=eA;Ads_sbid=k;xB(1,'Selected campaign',eA);xB(1,'Selected banner',k);xB(3,'Delivery and display of the banner');if(eA==64414)
{var kB=new Image();kB.src='http://as1.falkag.de/sel?cmd=ban&kid=70337&dat=122932&rdm=[timestamp]';}I=(I=='')?h:I;T=(G&24);U=C[G&3];X=((G&64)>0)&&((Ads_opt&64)==0);V=(G&128)>0;W=(G&512)>0;Y=((G&1024)>0)&&Ads_ModulEffects;Z=((G&8192)>0);Aa=(G&2048)>0;Ba=(Q.length>0);m=(Ads_xl>0)?Ads_xl:m;n=(Ads_yl>0)?Ads_yl:n;M=(Ads_xp!='')?Ads_xp:M;N=(Ads_yp!='')?Ads_yp:N;hA=(G&4096)>0;Ads_opt|=(G&16384)>0?64:0;Ads_opt|=IAS[3]*32;if(Ads_anc!='')
{y=true;B=Ads_anc;Ads_anc='';}Ads_Timestamp=uB();h=fB(h);I=fB(I);if(Ads_cnturl!='')
{Ca=wB(Ads_cnturl,'[url]',escape(h));h=wB(Ca,'[url_plain]',h);Ca=wB(Ads_cnturl,'[url]',escape(I));I=wB(Ca,'[url_plain]',I);}if(xA.length!=0)
{bA+=xA[13];cA+=xA[14];}i=qB(eA,k,A);xB(1,'Count-String',i);if((E==3)||(E==4))
{Ads_LinkUrl=h;Ads_CountUrl=hB('',i);Ads_ClickUrl=Ads_CountUrl+escape(h);Ads_MultiUrl=jB(p);Ads_ViewCode=sB(i);Ads_ViewUrl=rB()+i;}if(E==1)
J=mA[Ads_sec]+'/dat/bgf/'+D;if(xA.length!=0)
{if(!V)
{V=xA[0];X=xA[1];W=xA[2];P=xA[3];Y=xA[4];Z=xA[5];}if(!Ba)
{Ba=xA[6];Q=xA[7];}M=xA[8];N=xA[9];T=xA[10];IAS[2]=xA[11];IAS[11]=xA[12];B=xA[15];y=(B!='');xA=[];}if(E==5)
{xA=[V,X,W,P,Y,Z,Ba,Q,M,N,T,IAS[2],IAS[11],bA,cA,B];V=false;Ba=false;y=false;IAS[2]=0;}if((Ads_cmd=='lnk')&&(E!=5))
{self.location.href=hB(h,i);V=false;Ba=false;y=false;E=6;return;}if(V&&((S=='')||(E!=3)))
{v=lG(m,n,M,N,T,X,W,P,Y,Z);if(X)
{if(window.innerHeight)
{m=v.innerWidth;n=v.innerHeight;}else
{m=v.document.body.clientWidth;n=v.document.body.clientHeight;}}if(W)
window.setTimeout('v.blur();',P*1000);}else
v=window;if(y)
document.write(bC('Ads_place'+Ads_iid));else if(Ads_ModulEffects&&Ba)
{if(T==16)
T=1;else if(T==24)
T=2;else
T=0;sF(Ads_iid,m,n,M,N,T,Q,V,v);tF(Ads_iid,Ads_sec);}xB(1,'Banner-Typ/PopUp',E+'/'+V);if(E<2)
fG(v,V,i,J,h,U,m,n,F);else if(E==2)
gG(v,V,i,D,h,U,m,n,F,H,I,Aa,O);else if(E==3)
hG(v,V,i,eA,k,A,Ba,m,n,R,S,y,'/dat/brf/',0);else if(E==4)
iG(v,V,i,K,L,Ba,m,n,y);else if(E==5)
iB(eA,k,l,m,n);else if(E==8)
hG(v,V,i,eA,k,A,Ba,m,n,R,S,y,'/dat/afx/',parseInt(l,10));xB(3,'Banner-display finished');zC();if(y)
{document.write(cC());setInterval('eC("Ads_place'+Ads_iid+'","'+B+'",'+m+','+n+');',20);}if(Ads_ModulEffects&&Ba)
uF(Ads_iid);if(E!=5)
eB();Ads_idl+='#'+Ads_iid+'#';if((IAS[2]>0)&&(Ads_idl.indexOf('#'+IAS[2]+'#')==-1)&&(IAS[11]>(Math.random()*100)))
{xB(1,'Load adspot-combined adspot',IAS[2]);Ads_kid=0;Ads_bid=0;Ads_xl=0;Ads_yl=0;nB(jA[Ads_sec]+'/dat/cjf/'+yB(IAS[2])+'.js');}r=Ads_cmb.length;for(s=0;s<r;s++)
{if(Ads_cmb[s]!='')
{z=Ads_cmb[s];Ads_cmb[s]='';s=r;eval(z);xB(1,'Load tag-combined adspot',Ads_iid);nB(jA[Ads_sec]+'/dat/cjf/'+yB(Ads_iid)+'.js');}}}function CAS()
{if(typeof(Ads_debug)=='undefined') Ads_debug=0;var Da=new Date(Ads_T[9]);var Ea=new Date();Ads_T[9]=Da-Ea;var Fa=Ads_T[0]+'#'+Ads_T[1]+'#'+Ads_T[2]+'#'+Ads_T[3]+'#'+Ads_T[4]+'#'+Ads_T[5]+'#'+Ads_T[6]+'#'+escape(Ads_T[7])+'#'+escape(Ads_T[8])+'#'+Ads_T[9]+'#'+Ads_T[10]+'#'+Ads_T[11];document.cookie='ASLTRG='+Fa+oB(60*24);xB(1,'Load targeting-infos from server',Fa);}function LAS(Ga)
{Ads_iid=0;var i='pth='+Ga+'&xl='+Ads_xl+'&yl='+Ads_yl;if(typeof(Ads_channels)!='undefined')
i+='&chn='+escape(Ads_channels);hA=false;document.write(sB(i));}function lB()
{iA=new Date();if(typeof(Ads_debug)=='undefined') Ads_debug=0;if(typeof(Ads_sec)=='undefined') Ads_sec=0;if(typeof(Ads_klist)!='string') Ads_klist='';if(typeof(Ads_fcount)!='object') Ads_fcount=[];if(typeof(Ads_idl)!='string') Ads_idl='';xB(3,'Global Init');var Fa=document.cookie+';';var Ha=(Fa.indexOf('BSUID=')!=-1);var Ia=Fa.indexOf('ASLTRG=');var Ja,U;if(Ia!=-1)
{Ja=Fa.indexOf(';',Ia);U=Fa.substring(Ia+7,Ja);Ads_T=U.split('#');Ads_T[7]=unescape(Ads_T[7]);Ads_T[8]=unescape(Ads_T[8]);xB(1,'Load targeting-infos from cookie',U);}else
{xB(1,'#-#ASLDATA-load start','');nB(lA[Ads_sec]+(Ha?('?rdm='+uB()):''));xB(1,'#-#ASLDATA-load ende','');}}function mB(Ka,oLa,oMa)
{return true;}if((typeof(Ads_debug)=='undefined')||(Ads_debug!=1))
window.onerror=mB;lB();